// Model AI M Putra Ramadhani
// Disesuaikan untuk project M Putra Ramadhani - Ai Indonesia


export const CURATED_FREE_MODELS = [
  {
    id: "openrouter/free",
    name: "MPutraAI V6.1 Lunay",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Model ringan untuk percakapan dasar sehari-hari paket Free.",
    badge: "Free",
    tier: "free",
    recommended: true,
  },
  {
    id: "mputra/v61-gratis", name: "MPutraAI v6.1 Terra", provider: "M Putra Ramadhani", contextLength: "128K", description: "Versi gratis untuk percakapan, ide, dan kebutuhan harian.", badge: "Free", tier: "free", recommended: true,
  },
  {
    id: "mputra/v61-maya", name: "MPutraAI v6.1 Maya", provider: "M Putra Ramadhani", contextLength: "128K", description: "Versi gratis yang ringan dan responsif untuk percakapan harian.", badge: "Free", tier: "free", recommended: true,
  },
  {
    id: "mputra/v62-astras-thinking",
    name: "MPutraAI V6.2 Astras Thinking",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Penalaran mendalam dengan mode pemikiran intensif untuk analisis kompleks.",
    badge: "Deep Think",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v62-astras-flash",
    name: "MPutraAI V6.2 Astras Flash",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Kecepatan generasi kilat ultra tinggi dengan latensi super rendah.",
    badge: "Ultra Flash",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v62-astras-medium",
    name: "MPutraAI V6.2 Astras Medium",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Kecerdasan serbaguna generasi V6.2 terbaru untuk percakapan & produktivitas.",
    badge: "Unggulan",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v62-trunty-flash",
    name: "MPutraAI V6.2 Trunty Flash",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Konteks luas hingga 1M dengan kecepatan respons responsif dan akurat.",
    badge: "Responsif",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v62-dola",
    name: "MPutraAI V6.2 Dola",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Model obrolan seimbang, stabil, dan lancar untuk berbagai kebutuhan harian.",
    badge: "Seimbang",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v62-trunty-thinking",
    name: "MPutraAI V6.2 Trunty Thinking",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Penalaran logis bertahap dengan mode pemikiran terstruktur.",
    badge: "Nalar",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v61-auto",
    name: "MPutraAI V6.1 Lunai",
    provider: "M Putra Ramadhani",
    contextLength: "2M",
    description: "Memilih kemampuan terbaik secara otomatis untuk percakapan sehari-hari.",
    badge: "Unggulan",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v61-cepat",
    name: "MPutraAI V6.1 Fast",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Versi ringan untuk jawaban cepat dan pertanyaan singkat.",
    badge: "Cepat",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v61-analisis",
    name: "MPutraAI V6.1 Reason",
    provider: "M Putra Ramadhani",
    contextLength: "256K",
    description: "Untuk analisis terstruktur, tulisan, dan pemecahan masalah.",
    badge: "Analitis",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v61-lite",
    name: "MPutraAI V6.1 Lite",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Versi hemat untuk obrolan dan kebutuhan ringan.",
    badge: "Ringan",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v61-mini",
    name: "MPutraAI V6.1 Mini",
    provider: "M Putra Ramadhani",
    contextLength: "2M",
    description: "Konteks luas untuk percakapan panjang dan produktivitas.",
    badge: "Konteks Luas",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v61-flash",
    name: "MPutraAI V6.1 Flash",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Respons cepat untuk tugas harian dengan konteks panjang.",
    badge: "Responsif",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v61-vision",
    name: "MPutraAI V6.1 Vision",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Dapat membantu memahami foto dan dokumen visual.",
    badge: "Visual",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/v61-fokus",
    name: "MPutraAI V6.1 Focus",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Untuk jawaban fokus, rapi, dan percakapan berbasis teks.",
    badge: "Fokus",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/v61-peduli",
    name: "MPutraAI V6.1 Chat",
    provider: "M Putra Ramadhani",
    contextLength: "256K",
    description: "Pendamping percakapan yang hangat dan penuh perhatian.",
    badge: "Pendamping",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/cepat",
    name: "MPutraAI V5.9 Nano",
    provider: "M Putra Ramadhani",
    contextLength: "64K",
    description: "Versi paling ringan untuk respons singkat dengan latensi rendah.",
    badge: "Ringan",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/seimbang",
    name: "MPutraAI V5.9 Mini",
    provider: "M Putra Ramadhani",
    contextLength: "128K",
    description: "Versi ringkas yang seimbang untuk kebutuhan harian.",
    badge: "Efisien",
    tier: "plus",
    recommended: true,
  },
  {
    id: "mputra/kreatif",
    name: "MPutraAI V5.9 Agent",
    provider: "M Putra Ramadhani",
    contextLength: "256K",
    description: "Untuk alur kerja bertahap, tugas mandiri, dan perencanaan.",
    badge: "Agen",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/fokus",
    name: "MPutraAI V5.9 Code",
    provider: "M Putra Ramadhani",
    contextLength: "384K",
    description: "Untuk pemrograman, debugging, dan solusi yang terstruktur.",
    badge: "Kode",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/mendalam",
    name: "MPutraAI V5.9 Pro",
    provider: "M Putra Ramadhani",
    contextLength: "768K",
    description: "Untuk analisis rinci dan pekerjaan profesional sehari-hari.",
    badge: "Profesional",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/sempurna",
    name: "MPutraAI V5.9 Max",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Versi tertinggi untuk masalah kompleks dan kebutuhan penting.",
    badge: "Unggulan",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/petir",
    name: "MPutraAI V5.9 Speed",
    provider: "M Putra Ramadhani",
    contextLength: "512K",
    description: "Versi cepat dengan kapasitas konteks lebih luas.",
    badge: "Responsif",
    tier: "plus",
    recommended: false,
  },
  {
    id: "mputra/presisi",
    name: "MPutraAI V5.9 Precision",
    provider: "M Putra Ramadhani",
    contextLength: "640K",
    description: "Untuk jawaban teliti, rapi, dan kebutuhan berstruktur.",
    badge: "Presisi",
    tier: "plus",
    recommended: false,
  },
  {
    id: "nvidia/nemotron-3.5-lightning:free",
    name: "MPutraAI V6.0 Flash",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Respon super responsif & instan untuk percakapan tingkat lanjut.",
    badge: "Sangat Cepat",
    tier: "plus",
    recommended: true,
  },
  {
    id: "google/gemma-4-31b-it:free",
    name: "MPutraAI V6.0 Reason",
    provider: "M Putra Ramadhani",
    contextLength: "262K",
    description: "Penalaran tingkat tinggi dan kemampuan pemahaman teks mendalam.",
    badge: "Pintar & Nalar",
    tier: "plus",
    recommended: true,
  },
  {
    id: "google/gemma-4-26b-a4b-it:free",
    name: "MPutraAI V6.0",
    provider: "M Putra Ramadhani",
    contextLength: "262K",
    description: "Obrolan santai seimbang, ramah, dan hemat latensi.",
    badge: "Seimbang",
    tier: "plus",
    recommended: true,
  },
  {
    id: "nvidia/nemotron-3-ultra-550b-a55b:free",
    name: "MPutraAI V6.0 Max",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Kapasitas raksasa 550B untuk analisis mendalam & pertanyaan kompleks.",
    badge: "Kapasitas Raksasa",
    tier: "plus",
    recommended: true,
  },
  {
    id: "nvidia/nemotron-3-super-120b-a12b:free",
    name: "MPutraAI V6.0 Logic",
    provider: "M Putra Ramadhani",
    contextLength: "262K",
    description: "Logika analitis tangguh dan pemikiran terstruktur.",
    badge: "Logika Kuat",
    tier: "plus",
    recommended: false,
  },
  {
    id: "minimax/minimax-m3:free",
    name: "MPutraAI V6.0 Chat",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Karakter ekspresif, hangat, dan alami untuk teman mengobrol.",
    badge: "Ekspresif",
    tier: "plus",
    recommended: true,
  },
  {
    id: "minimax/minimax-m2.7:free",
    name: "MPutraAI V6.0 Creative",
    provider: "M Putra Ramadhani",
    contextLength: "196K",
    description: "Respon luwes, kreatif, dan dinamis untuk ide serta tulisan.",
    badge: "Kreatif",
    tier: "plus",
    recommended: false,
  },
  {
    id: "thinkingmachines/inkling:free",
    name: "MPutraAI V6.0 Long",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Kemampuan interaktif serbaguna dengan konteks ultra panjang.",
    badge: "Fleksibel",
    tier: "plus",
    recommended: false,
  },
  {
    id: "thinkingmachines/inkling-small:free",
    name: "MPutraAI V6.0 Lite",
    provider: "M Putra Ramadhani",
    contextLength: "1M",
    description: "Versi gesit dengan performa efisien tingkat tinggi.",
    badge: "Ringan",
    tier: "plus",
    recommended: false,
  },
  {
    id: "cohere/north-mini-code:free",
    name: "MPutraAI V6.0 Code",
    provider: "M Putra Ramadhani",
    contextLength: "256K",
    description: "Spesialis logika pemrograman, debugging kode, dan algoritma.",
    badge: "Kode & Logika",
    tier: "plus",
    recommended: false,
  },
  {
    id: "liquid/lfm-2.5-2.6b:free",
    name: "MPutraAI V6.0 Nano",
    provider: "M Putra Ramadhani",
    contextLength: "65K",
    description: "Arsitektur neural ringkas dengan efisiensi respon tingkat tinggi.",
    badge: "Efisien",
    tier: "plus",
    recommended: false,
  },
];


const STORAGE_KEY = "val_ai_selected_model";
const DEFAULT_MODEL = "openrouter/free";

export function getSavedModel() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (saved) return saved;
  } catch {}
  return DEFAULT_MODEL;
}

export function saveModel(modelId) {
  try {
    localStorage.setItem(STORAGE_KEY, modelId);
  } catch {}
}

export function findModel(modelId, customList = CURATED_FREE_MODELS) {
  const found = customList.find((m) => m.id === modelId);
  if (found) return found;
  const rawName = modelId.split("/").pop()?.replace(":free", "") || modelId;
  return {
    id: modelId,
    name: rawName.startsWith("M Putra") ? rawName : `M Putra Ramadhani ${rawName}`,
    provider: "M Putra Ramadhani",
    contextLength: "Free",
    description: "Model kecerdasan M Putra Ramadhani.",
    badge: "Free",
    tier: modelId === DEFAULT_MODEL ? "free" : "plus",
  };
}
